language: python
python:
    - "2.7"
    - "3.5"
install:
    - pip install -r requirements.txt
    - USE_CYTHON=1 python setup.py build_ext --inplace -f install
# actual test run can be added later
script:
    - py.test -v ./test
